name: Build and deploy .NET Core application to Web App bendaygithubdemo
on:
  workflow_dispatch:
  push:
    branches:
    - main
env:
  AZURE_WEBAPP_NAME: bendaygithubdemo
  AZURE_WEBAPP_PACKAGE_PATH: Benday.CalculatorDemo.WebUi/published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WORKING_DIRECTORY: Benday.CalculatorDemo
  WEBAPP_WORKING_DIRECTORY: Benday.CalculatorDemo/Benday.CalculatorDemo.WebUi
  AZURE_WEBAPP_RESOURCE_GROUP: rg-github-demo
  AZURE_WEBAPP_SLOT_NAME: test
  UNIT_TESTS_WORKING_DIRECTORY: Benday.CalculatorDemo/Benday.CalculatorDemo.UnitTests

jobs:
  build:
    uses: ./build.yml@main

  deploy-to-test:
    # runs-on: windows-latest
    runs-on: self-hosted
    needs: build
    environment: test
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4.1.7
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v3.0.1
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.PUBLISH_PROFILE_TEST }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        slot-name: 'test'
    - name: Log into Azure CLI with service principal
      uses: azure/login@v2.1.0
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: set version info
      run: az webapp config appsettings set -n ${{ env.AZURE_WEBAPP_NAME }} -g ${{ env.AZURE_WEBAPP_RESOURCE_GROUP }} --settings "BuildVersionMessage=${{ github.run_number }}.deploy-to-test"
  deploy-to-prod:
    # runs-on: windows-latest
    runs-on: self-hosted
    environment: prod
    needs: deploy-to-test
    steps:
    - name: Log into Azure CLI with service principal
      uses: azure/login@v2.1.0
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Swap slots
      run: az webapp deployment slot swap -s ${{ env.AZURE_WEBAPP_SLOT_NAME }} -n ${{ env.AZURE_WEBAPP_NAME }} -g ${{ env.AZURE_WEBAPP_RESOURCE_GROUP }}

    - name: set version info
      run: az webapp config appsettings set -n ${{ env.AZURE_WEBAPP_NAME }} -g ${{ env.AZURE_WEBAPP_RESOURCE_GROUP }} --settings "BuildVersionMessage=${{ github.run_number }}.deploy-to-prod"
