name: Build and deploy .NET Core application to Web App bendaygithubdemo
on:
  pull_request:
    types: [opened, synchronize, reopened]
  
env:
  AZURE_WEBAPP_NAME: bendaygithubdemo
  AZURE_WEBAPP_PACKAGE_PATH: Benday.CalculatorDemo.WebUi/published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WORKING_DIRECTORY: Benday.CalculatorDemo
  WEBAPP_WORKING_DIRECTORY: Benday.CalculatorDemo/Benday.CalculatorDemo.WebUi
  AZURE_WEBAPP_RESOURCE_GROUP: rg-github-demo
  AZURE_WEBAPP_SLOT_NAME: test
  UNIT_TESTS_WORKING_DIRECTORY: Benday.CalculatorDemo/Benday.CalculatorDemo.UnitTests

jobs:
  build:
    uses: ./.github/workflows/build.yml

  